export const ADD_CLAIM_REQUEST = 'ADD_CLAIM_REQUEST'
export const ADD_CLAIM_SUCCESS = 'ADD_CLAIM_SUCCESS'
export const ADD_CLAIM_FAILED = 'ADD_CLAIM_FAILED'

export const ADD_REPLY_REQUEST = 'ADD_REPLY_REQUEST'
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS'
export const ADD_REPLY_FAILED = 'ADD_REPLY_FAILED'

export const ADD_UNCLAIM_REQUEST = 'ADD_UNCLAIM_REQUEST'
export const ADD_UNCLAIM_SUCCESS = 'ADD_UNCLAIM_SUCCESS'
export const ADD_UNCLAIM_FAILED = 'ADD_UNCLAIM_FAILED'

export const COLLECT_ADD_REQUEST = 'COLLECT_ADD_REQUEST'
export const COLLECT_ADD_SUCCESS = 'COLLECT_ADD_SUCCESS'
export const COLLECT_ADD_FAILED = 'COLLECT_ADD_FAILED'

export const ADD_SHARE_REQUEST = 'ADD_SHARE_REQUEST'
export const ADD_SHARE_SUCCESS = 'ADD_SHARE_SUCCESS'
export const ADD_SHARE_FAILED = 'ADD_SHARE_FAILED'