export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const WALLET_NOT_FOUND = 'WALLET_NOT_FOUND'
export const USER_RESETTING_LOGIN = 'USER_RESETTING_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const FETCH_ALL_ADS_REQUEST = 'FETCH_ALL_ADS_REQUEST'
export const FETCH_ALL_ADS_SUCCESS = 'FETCH_ALL_ADS_SUCCESS'
export const FETCH_ALL_ADS_FAIL = 'FETCH_ALL_ADS_FAIL'

export const FETCH_ADD_BY_ID_REQUEST = 'FETCH_ADD_BY_ID_REQUEST'
export const FETCH_ADD_BY_ID_SUCCESS = 'FETCH_ADD_BY_ID_SUCCESS'
export const FETCH_ADD_BY_ID_FAIL = 'FETCH_ADD_BY_ID_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST'
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'
export const GET_NOTIFICATION_FAILED = 'GET_NOTIFICATION_FAILED'

export const GET_USER_ACTIVITY_REQUEST = 'GET_USER_ACTIVITY_REQUEST'
export const GET_USER_ACTIVITY_SUCCESS = 'GET_USER_ACTIVITY_SUCCESS'
export const GET_USER_ACTIVITY_FAILED = 'GET_USER_ACTIVITY_FAILED'

export const GLOBAL_SEARCH_REQUEST = 'GLOBAL_SEARCH_REQUEST'
export const GLOBAL_SEARCH_SUCCESS = 'GLOBAL_SEARCH_SUCCESS'
export const GLOBAL_SEARCH_FAIL = 'GLOBAL_SEARCH_FAIL'